sudo: required
language: generic
services:
   - docker
before_install:
   - echo "$DOCKER_ID"
   - echo "$DOCKER_PASSWORD"
   - docker build -t sakthi/react-test -f ./client/Dockerfile.dev ./client   

script:
   - docker run -e CI=true sakthi/react-test npm test

after_success:   
   - docker build -t sakthivigneshrsv/multi-client ./client
   - docker build -t sakthivigneshrsv/multi-nginx ./nginx
   - docker build -t sakthivigneshrsv/multi-server ./server
   - docker build -t sakthivigneshrsv/multi-worker ./worker
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   - docker push sakthivigneshrsv/multi-client
   - docker push sakthivigneshrsv/multi-nginx
   - docker push sakthivigneshrsv/multi-server
   - docker push sakthivigneshrsv/multi-worker
